apiVersion: v1
kind: Pod
metadata:
  labels:
    why: test-the-opentelemetry-collector
  name: otel-test-pod
spec:
  containers:
    - args:
        - sleep
        - "3600"
      image: jessitron/otel-test-pod
      name: otel-test-pod
      resources: {}
      env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
  dnsPolicy: ClusterFirst
  restartPolicy: Never
